### ISSUE TITLE
勝手にログインされている状況について

### ISSUE THREAD

**Issue by kogepanh** [RyoichiNakai/lab-assignment#103]
@RyoichiNakai @uzumal

開発状況とかよくわかってないですが，たまたま覗いてみたら気になったので一応，報告ですー

dev, prod 共に，最初から勝手にログインされています

![スクリーンショット 2021-12-13 170542](https://user-images.githubusercontent.com/49851726/145774852-429f3465-4668-44e4-b065-9641132c8ed7.jpg)

**Comment by RyoichiNakai** [comment]
ログイン機能開発できたんで、閉じます。
